# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Zach/Documents/GradSchool/Fall_2019/EN525.742_SOC_Design_Lab/EN525.742_Project_4/EN525.742_Project_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
