# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/project1_zedboard.xdc

# XDC: imports/Downloads/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/proc_system/proc_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system || ORIG_REF_NAME==proc_system} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_microblaze_0_0/proc_system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_microblaze_0_0 || ORIG_REF_NAME==proc_system_microblaze_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_mdm_1_0/proc_system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_mdm_1_0 || ORIG_REF_NAME==proc_system_mdm_1_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_rst_Clk_100M_0/proc_system_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_rst_Clk_100M_0 || ORIG_REF_NAME==proc_system_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_dlmb_v10_0/proc_system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_dlmb_v10_0 || ORIG_REF_NAME==proc_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_ilmb_v10_0/proc_system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_ilmb_v10_0 || ORIG_REF_NAME==proc_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_dlmb_bram_if_cntlr_0/proc_system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==proc_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_ilmb_bram_if_cntlr_0/proc_system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==proc_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_lmb_bram_0/proc_system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_lmb_bram_0 || ORIG_REF_NAME==proc_system_lmb_bram_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_uartlite_0_0/proc_system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_uartlite_0_0 || ORIG_REF_NAME==proc_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_microblaze_0_axi_periph_0/proc_system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==proc_system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_quad_spi_0_0/proc_system_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_quad_spi_0_0 || ORIG_REF_NAME==proc_system_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_xbar_0/proc_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_xbar_0 || ORIG_REF_NAME==proc_system_xbar_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/proc_system/proc_system_ooc.xdc
